spring.application.name=ms-os-automation

server.port=8580

spring.cloud.consul.host=consul-server
spring.cloud.consul.port=8500

# Register this service in Consul
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
# Expose health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.kafka.bootstrap-servers=kafka:9092